### ISSUE TITLE
Can't remove servers (Mac)

### ISSUE THREAD

**Issue by burtonkent** [technicallyerik/WIRK#12]
ctrl-clicking on the server in the right side server list brings up a small dropdown for "connect" or "remove".  The "remove" doesn't work. I did try restarting the program to see if it makes a difference.

**Comment by Bendetta** [comment]
Erik can't reproduce this and I don't have a Mac - can you show him next time you're in?

**Comment by burtonkent** [comment]
Will do.

**Comment by davidkam** [comment]
Worked on my Mac without a problem.

**Comment by burtonkent** [comment]
Very strange - I just tried yet again - added a new server first. Still no luck. Will demonstrate when I'm in on Monday.

**Comment by technicallyerik** [comment]
This is related to the fact that you can add multiple servers with the same host name.  Our server lookup fails on delete if there isn't exactly one server.  We should probably fix both issues related to this.
