### ISSUE TITLE
Most IRC commands don't seem to work.

### ISSUE THREAD

**Issue by davidkam** [technicallyerik/WIRK#16]
http://en.wikipedia.org/wiki/List_of_Internet_Relay_Chat_commands

JOIN seems to be one of the few that works.

If you want, I can go down and test the entire list if you want.

**Comment by Bendetta** [comment]
/join, /part, /topic, /me (currently broken) and /invite are implemented according to the RFC, but the rest will need to be implemented.

**Comment by davidkam** [comment]
Erik showed me the code.  Looks like there are placeholders there.  I'll try to help out with some of those.

**Comment by Bendetta** [comment]
Almost all the place holders have been filled in now. We'll have to figure out a way to handle /names, and the Client-to-Client stuff isn't implemented yet, as well as /CAP which I can't figure out what that is. It looks like if we want to implement a lot of those others IRC commands from the wikipedia page, we'll have to extend the IRC framework we're using.
