### ISSUE TITLE
Channels sometimes no longer display text

### ISSUE THREAD

**Issue by Bendetta** [technicallyerik/WIRK#23]
I think this might be windows only, but leaving a channel with a lot of activity on for awhile (#chicago in my case), I switch to another channel and back to #chicago and chicago will no longer display the previous text. It will display new text, but when I switch channels and come back, that new text is gone as well.

This will probably be fixed when we implement our new solution for #8, but leaving it here as an acknowledgement

**Comment by davidkam** [comment]
This also happens in Mac.
