### ISSUE TITLE
image, video, blog previews go away when joining a new channel

### ISSUE THREAD

**Issue by temartin** [technicallyerik/WIRK#32]
1. join a channel: /join #chan1
2. post an image
3. observe working preview
4. from #chan1, join another channel: /join #chan2
5. return to first channel, #chan1
6. observe that the preview is now broken and just a small icon is shown

**Comment by technicallyerik** [comment]
I think this is caused my switching initialization of rooms and servers to have no text.  The QTextDocument must release all images from memory when this happens.  Will initialize servers and rooms with some dummy tag.
