### ISSUE TITLE
Upgrading removes existing servers

### ISSUE THREAD

**Issue by designatednerd** [technicallyerik/WIRK#42]
Upgrading from 0.1.1 to 0.2 by dragging the 0.2 into /Applications nuked all servers and channels. 

Expected behavior: Version upgrades should not alter this info.

**Comment by technicallyerik** [comment]
Although we could have done it more seamlessly for the upgrade from 0.1.1. to 0.2, this was a one time thing.

We moved the file inside the user's home directory to make future upgrades easier, improve security, and address issues if WIRK was installed to 'Applications' on a MAC or 'Program Files' on a PC.

You can move your wirk.ini file to the following new locations:

MAC: $HOME/.config/com.flashforwardlabs
PC: %APPDATA%\Roaming\com.flashforwardlabs.
