### ISSUE TITLE
"Kick" Issues

### ISSUE THREAD

**Issue by technicallyerik** [technicallyerik/WIRK#44]
Kick doesn't work if there is a space after the person's name.  The message for a kicked recipient appears to be wrong (sounds like you got kicked by yourself)

**Comment by nwhobart** [comment]
bliset has left #chicago (Reason: Kicked by nhobart (Reason: nhobart))

this is primarily an issue because tab-completing a name results in a space after the name is selected.

**Comment by technicallyerik** [comment]
Yeah, I think if we just trim the command before we start processing it, we should be good.
