### ISSUE TITLE
Create a hotkey to cycle through currently open channels

### ISSUE THREAD

**Issue by creativedrewy** [technicallyerik/WIRK#53]
Requesting a feature that would allow the user to cycle through the channels they currently have open via a hotkey. This would allow the user to quickly see what is going on in their channels without needed the mouse.

Suggested hotkey(s) would be Alt key plus left/right arrows. Left arrow would move up in the list, right arrow would move down.

**Comment by Bendetta** [comment]
I'm a fan of this idea. Wouldn't ctrl + tab and ctrl + shift + tab be more inline with most programs though? That tends to be the default for most on Windows programs, such as changing your tabs in your browser. I can't speak for Macs.

**Comment by nt-complete** [comment]
Yeah, Ben, you're right. I think Ctrl+tab is the best way to go with this.
